\ Auto-generated SASS vocabulary for sm_90
\ Generated by sass_probe.py

\ --- Opcode constants ---

$7209 constant OP-FMNMX
$720b constant OP-FSETP
$7220 constant OP-FMUL
$7221 constant OP-FADD
$7223 constant OP-FFMA
$723c constant OP-HMMA
$7308 constant OP-MUFU
$7388 constant OP-STS
$7421 constant OP-FADD-IMM
$7835 constant OP-HFMA2
$783b constant OP-LDSM
$791a constant OP-DEPBAR
$7984 constant OP-LDS
$7992 constant OP-MEMBAR
$79af constant OP-LDGDEPBAR
$7b1d constant OP-BAR
$7f89 constant OP-SHFL
$7fae constant OP-LDGSTS

\ --- Instruction emitter words ---

\ FMNMX: min.f32 rd, rs1, rs2
: fmnmx,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7209 or r> or r> or
  $000fc00000000000 sinst, ;

\ FSETP: setp.gt.f32 pd, rs1, rs2
: fsetp,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $720b or r> or r> or
  $000fc00000000000 sinst, ;

\ FMUL: mul.f32 rd, rs1, rs2
: fmul,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7220 or r> or r> or
  $000fc00000000000 sinst, ;

\ FADD: add.f32 rd, rs1, rs2
: fadd,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7221 or r> or r> or
  $000fc00000000000 sinst, ;

\ FFMA: fma.rn.f32 rd, rs1, rs2, rs3
: ffma,  ( rd rs1 rs2 rs3 -- )
  >r                    \ rs3 saved for ctrl word
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7223 or r> or r> or
  $000fca0000000000 r> or sinst, ;
  \ NOTE: rs3 goes into ctrl[7:0]

\ MUFU: cos.approx.f32 rd, rs1
: mufu,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or r> or
  $000fc00000000000 sinst, ;

\ FADD-IMM: add.f32 rd, rs1, 1.0
: fadd-imm,  ( rd rs1 imm32 -- )
  32 lshift >r          \ imm32 -> bits [63:32]
  24 lshift >r          \ rs1   -> bits [31:24]
  16 lshift             \ rd    -> bits [23:16]
  $7421 or r> or r> or
  $000fc00000000000 sinst, ;

\ HFMA2: add.rn.f16x2 rd, rs1, rs2
: hfma2,  ( rd rs1 rs2 rs3 -- )
  >r                    \ rs3 saved for ctrl word
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7835 or r> or r> or
  $000fca0000000000 r> or sinst, ;
  \ NOTE: rs3 goes into ctrl[7:0]

\ --- MUFU sub-functions ---
\ All share opcode 0x308, sub-function in ctrl[13:10]

: mufu_cos,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000000000 sinst, ;

: mufu_sin,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000000400 sinst, ;

: mufu_ex2,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000000800 sinst, ;

: mufu_lg2,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000000c00 sinst, ;

: mufu_rcp,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000001000 sinst, ;

: mufu_rsq,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000001400 sinst, ;

: mufu_sqrt,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000002000 sinst, ;

\ --- Predicate guard helpers ---
\ Apply predicate to an instruction word
: @p0  ( inst -- inst' )  $FFFFF0FF and $00000000 or ;  \ @P0
: @p1  ( inst -- inst' )  $FFFFF0FF and $00001000 or ;  \ @P1
: @p2  ( inst -- inst' )  $FFFFF0FF and $00002000 or ;  \ @P2
: @p3  ( inst -- inst' )  $FFFFF0FF and $00003000 or ;  \ @P3
: @!p0 ( inst -- inst' )  $FFFFF0FF and $00008000 or ;  \ @!P0
: @!p1 ( inst -- inst' )  $FFFFF0FF and $00009000 or ;  \ @!P1
: @!p2 ( inst -- inst' )  $FFFFF0FF and $0000A000 or ;  \ @!P2
: @!p3 ( inst -- inst' )  $FFFFF0FF and $0000B000 or ;  \ @!P3

\ --- Register constants ---
$FF constant RZ  \ Zero register (R255)

\ ============================================================
\ GEMV OPERATIONS — LDG, STG, IMAD, SHFL.BFLY, BRA, ISETP
\ Encodings verified against probe disassembly (probe*.sass)
\ ============================================================

\ Opcode constants for new ops (matching existing naming convention)
$7981 constant OP-LDG
$7986 constant OP-STG
$7c24 constant OP-IMAD
$7424 constant OP-IMAD-IMM
$7947 constant OP-BRA
$7c0c constant OP-ISETP

\ LDG.E Rd, [Ra]  — 32-bit global load, no offset
\ Verified: LDG.E R0, [R2.64] -> inst=0x0000000402007981 ctrl=0x000ea8000c1e1900
: ldg,  ( rd ra -- )
  24 lshift >r              \ ra -> bits[31:24]
  16 lshift                 \ rd -> bits[23:16]
  OP-LDG or r> or
  $000ea8000c1e1900 sinst, ;

\ LDG.E Rd, [Ra+off]  — 32-bit global load with immediate byte offset
\ Verified: LDG.E R5, [R2.64+0x4] -> 0x0000040402057981 (off<<32 | ra<<24 | rd<<16)
: ldg-off,  ( rd ra off -- )
  32 lshift >r              \ off -> bits[47:32]
  24 lshift >r              \ ra  -> bits[31:24]
  16 lshift                 \ rd  -> bits[23:16]
  OP-LDG or r> or r> or
  $000ea8000c1e1900 sinst, ;

\ STG.E [Ra], Rs  — 32-bit global store, no offset
\ Verified: STG.E [R6.64], R9 -> inst=0x0000000906007986 ctrl=0x000fe2000c101904
: stg,  ( ra rs -- )
  32 lshift >r              \ rs -> bits[39:32]
  24 lshift                 \ ra -> bits[31:24]
  OP-STG or r> or
  $000fe2000c101904 sinst, ;

\ STG.E [Ra+off], Rs  — 32-bit global store with immediate byte offset
\ Verified: STG.E [R2+0x4], R7 -> 0x0000040702007986
: stg-off,  ( ra rs off -- )
  32 lshift >r              \ off -> bits[47:32]
  swap 32 lshift >r         \ rs  -> bits[39:32]
  24 lshift                 \ ra  -> bits[31:24]
  OP-STG or r> or r> or
  $000fe2000c101904 sinst, ;

\ IMAD Rd, Rs1, Rs2, Rs3  — integer multiply-add (reg*reg+reg)
\ Verified: IMAD R0, R3, UR4, R0 -> inst=0x0000000403007c24 ctrl contains rs3
\ Rs3 (accumulator) goes in ctrl[7:0] per ENCODING.md 4-operand format
: imad,  ( rd rs1 rs2 rs3 -- )
  >r                        \ rs3 saved for ctrl[7:0]
  32 lshift >r              \ rs2 -> bits[39:32]
  24 lshift >r              \ rs1 -> bits[31:24]
  16 lshift                 \ rd  -> bits[23:16]
  OP-IMAD or r> or r> or
  $000fc00000000000 r> or sinst, ;

\ IMAD-IMM Rd, Rs1, imm32  — integer multiply by immediate + RZ
\ Verified: IMAD.MOV.U32 R9, RZ, RZ, imm -> 0x{imm}ff097424
\ For general IMAD with imm accumulator: opcode $7424, Rs2=RZ in ctrl
: imad-imm,  ( rd rs1 imm32 -- )
  32 lshift >r              \ imm32 -> bits[63:32]
  24 lshift >r              \ rs1   -> bits[31:24]
  16 lshift                 \ rd    -> bits[23:16]
  OP-IMAD-IMM or r> or r> or
  $000fc000000000ff sinst, ;

\ SHFL.BFLY PT, Rd, Rs, delta  — warp butterfly shuffle (imm delta, mask=0x1f)
\ Verified: SHFL.BFLY PT, R5, R0, 0x1, 0x1f -> inst=0x0c201f0000057f89
\   bits[63:56] = (log2(delta)<<4)|0x0c  clamp=0x20 at [55:48], mask=0x1f at [47:40]
\   bits[31:24]=Rs, bits[23:16]=Rd, bits[15:0]=$7f89
\ ctrl from probe_6b: $001e6800000e0000
: shfl-bfly,  ( rd rs delta -- )
  dup 1 = if drop 0 else
  dup 2 = if drop 1 else
  dup 4 = if drop 2 else
  dup 8 = if drop 3 else
             drop 4
  then then then then
  4 lshift $0c or
  56 lshift >r              \ mode_byte -> bits[63:56]
  24 lshift >r              \ rs -> bits[31:24]
  16 lshift                 \ rd -> bits[23:16]
  $7f89 or r> or
  $1f 40 lshift or           \ mask=0x1f at [47:40]
  $20 48 lshift or           \ clamp=0x20 at [55:48]
  r> or
  $001e6800000e0000 sinst, ;

\ SHFL.DOWN PT, Rd, Rs, delta  — warp down-shuffle (fixed delta=1)
\ Verified: SHFL.DOWN PT, R7, R0, 0x1, 0x1f -> 0x08201f0000077f89
\   bits[63:56]=0x08(DOWN), clamp=0x20 at [55:48], mask=0x1f at [47:40]
\ ctrl from probe: $000e2800000e0000
: shfl-down,  ( rd rs delta -- )
  drop                      \ delta unused — only verified for delta=1
  24 lshift >r              \ rs -> bits[31:24]
  16 lshift                 \ rd -> bits[23:16]
  $7f89 or r> or
  $1f 40 lshift or
  $20 48 lshift or
  $0800000000000000 or
  $000e2800000e0000 sinst, ;

\ BRA offset32  — branch PC-relative (signed byte offset from next instruction)
\ Verified: BRA loop -> inst=0xfffffffc00fc7947 ctrl=0x000fc0000383ffff
\ bits[63:32]=offset, bits[23:16]=0xfc, bits[31:24]=0x00, lower=0x7947
: bra,  ( offset32 -- )
  32 lshift $00fc7947 or
  $000fc0000383ffff sinst, ;

\ @Px BRA offset32  — predicated branch
\ pred = 0..3 for P0..P3
: bra-pred,  ( offset32 pred -- )
  12 lshift >r
  32 lshift $00fc7947 or
  $FFFF0FFF and r> or
  $000fc0000383ffff sinst, ;

\ ISETP.GE.U32.AND Pd, PT, Rs1, Rs2, PT  — integer >= set predicate
\ Verified: ISETP.GE.U32.AND P0, PT, R0, UR4, PT -> inst=0x0000000400007c0c
\   bits[23:16]=Pd, bits[31:24]=Rs1, bits[39:32]=Rs2, opcode=$7c0c
\ ctrl from probe: $000fda000bf06070  (encodes GE+U32+AND)
: isetp-ge,  ( pd rs1 rs2 -- )
  32 lshift >r              \ rs2 -> bits[39:32]
  24 lshift >r              \ rs1 -> bits[31:24]
  16 lshift                 \ pd  -> bits[23:16]
  OP-ISETP or r> or r> or
  $000fda000bf06070 sinst, ;

\ ISETP.LT.U32.AND Pd, PT, Rs1, Rs2, PT  — integer < set predicate
\ ctrl for LT: same opcode, different ctrl comparison mode nibble
: isetp-lt,  ( pd rs1 rs2 -- )
  32 lshift >r
  24 lshift >r
  16 lshift
  OP-ISETP or r> or r> or
  $000fda000bf02070 sinst, ;

\ ============================================================
\ WARP SUM-REDUCE HELPER  (GEMV warp reduction pattern)
\ Performs 5-step butterfly reduce across 32 lanes using SHFL.BFLY + FADD.
\ acc: register with partial sum (holds result in lane 0 after)
\ tmp: scratch register
\ ============================================================
: warp-reduce,  ( acc tmp -- )
  over over  16 shfl-bfly   ( -- acc tmp )
  over over swap fadd,
  over over   8 shfl-bfly
  over over swap fadd,
  over over   4 shfl-bfly
  over over swap fadd,
  over over   2 shfl-bfly
  over over swap fadd,
  over over   1 shfl-bfly
  over over swap fadd,
  2drop ;
