\ Auto-generated SASS vocabulary for sm_90
\ Generated by sass_probe.py

\ --- Opcode constants ---

$7209 constant OP-FMNMX
$720b constant OP-FSETP
$7220 constant OP-FMUL
$7221 constant OP-FADD
$7223 constant OP-FFMA
$723c constant OP-HMMA
$7308 constant OP-MUFU
$7388 constant OP-STS
$7421 constant OP-FADD-IMM
$7835 constant OP-HFMA2
$783b constant OP-LDSM
$791a constant OP-DEPBAR
$7984 constant OP-LDS
$7992 constant OP-MEMBAR
$79af constant OP-LDGDEPBAR
$7b1d constant OP-BAR
$7f89 constant OP-SHFL
$7fae constant OP-LDGSTS

\ --- Instruction emitter words ---

\ FMNMX: min.f32 rd, rs1, rs2
: fmnmx,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7209 or r> or r> or
  $000fc00000000000 sinst, ;

\ FSETP: setp.gt.f32 pd, rs1, rs2
: fsetp,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $720b or r> or r> or
  $000fc00000000000 sinst, ;

\ FMUL: mul.f32 rd, rs1, rs2
: fmul,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7220 or r> or r> or
  $000fc00000000000 sinst, ;

\ FADD: add.f32 rd, rs1, rs2
: fadd,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7221 or r> or r> or
  $000fc00000000000 sinst, ;

\ FFMA: fma.rn.f32 rd, rs1, rs2, rs3
: ffma,  ( rd rs1 rs2 rs3 -- )
  >r                    \ rs3 saved for ctrl word
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7223 or r> or r> or
  $000fca0000000000 r> or sinst, ;
  \ NOTE: rs3 goes into ctrl[7:0]

\ MUFU: cos.approx.f32 rd, rs1
: mufu,  ( rd rs1 rs2 -- )
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or r> or
  $000fc00000000000 sinst, ;

\ FADD-IMM: add.f32 rd, rs1, 1.0
: fadd-imm,  ( rd rs1 imm32 -- )
  32 lshift >r          \ imm32 -> bits [63:32]
  24 lshift >r          \ rs1   -> bits [31:24]
  16 lshift             \ rd    -> bits [23:16]
  $7421 or r> or r> or
  $000fc00000000000 sinst, ;

\ HFMA2: add.rn.f16x2 rd, rs1, rs2
: hfma2,  ( rd rs1 rs2 rs3 -- )
  >r                    \ rs3 saved for ctrl word
  32 lshift >r          \ rs2 -> bits [39:32]
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7835 or r> or r> or
  $000fca0000000000 r> or sinst, ;
  \ NOTE: rs3 goes into ctrl[7:0]

\ --- MUFU sub-functions ---
\ All share opcode 0x308, sub-function in ctrl[13:10]

: mufu_cos,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000000000 sinst, ;

: mufu_sin,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000000400 sinst, ;

: mufu_ex2,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000000800 sinst, ;

: mufu_lg2,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000000c00 sinst, ;

: mufu_rcp,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000001000 sinst, ;

: mufu_rsq,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000001400 sinst, ;

: mufu_sqrt,  ( rd rs1 -- )
  24 lshift >r          \ rs1 -> bits [31:24]
  16 lshift             \ rd  -> bits [23:16]
  $7308 or r> or        \ opcode + pred PT
  $000fc00000002000 sinst, ;

\ --- Predicate guard helpers ---
\ Apply predicate to an instruction word
: @p0  ( inst -- inst' )  $FFFFF0FF and $00000000 or ;  \ @P0
: @p1  ( inst -- inst' )  $FFFFF0FF and $00001000 or ;  \ @P1
: @p2  ( inst -- inst' )  $FFFFF0FF and $00002000 or ;  \ @P2
: @p3  ( inst -- inst' )  $FFFFF0FF and $00003000 or ;  \ @P3
: @!p0 ( inst -- inst' )  $FFFFF0FF and $00008000 or ;  \ @!P0
: @!p1 ( inst -- inst' )  $FFFFF0FF and $00009000 or ;  \ @!P1
: @!p2 ( inst -- inst' )  $FFFFF0FF and $0000A000 or ;  \ @!P2
: @!p3 ( inst -- inst' )  $FFFFF0FF and $0000B000 or ;  \ @!P3

\ --- Register constants ---
$FF constant RZ  \ Zero register (R255)
