#!/usr/bin/env bash
# build.sh — Assemble and link the Lithos bootstrap.
#
# Input: the .s sources in this directory.
# Output: ./lithos-bootstrap (ARM64 static ELF).
#
# The sources were originally written to be concatenated together.
# This script links them as separate .o files instead, which requires
# two build-time patches:
#
#   1. lithos-lexer.s and lithos-expr.s use the NEXT / PUSH / POP
#      macros but do not define them. We prepend a macro header
#      before assembly.
#
#   2. lithos-bootstrap.s defines _start, but driver.s also defines
#      _start (and supersedes it). We rename bootstrap's _start to
#      bootstrap_init via sed.
#
#   3. GAS defaults labels to LOCAL binding. Most cross-file
#      references (code_*, entry_*, var_*, main_loop, last_entry,
#      etc.) need to be promoted to GLOBAL. We auto-generate a
#      per-file globals prelude.
#
# The original sources on disk are never modified — patched copies
# live under build/.

set -euo pipefail

cd "$(dirname "$0")"

BUILD=build
SRCS=(
    ls-shared.s
    lithos-bootstrap.s
    lithos-lexer.s
    lithos-table.s
    lithos-expr.s
    emit-arm64.s
    lithos-elf-writer.s
    lithos-glue.s
    driver.s
)

red()   { printf '\033[31m%s\033[0m\n' "$*" >&2; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }

rm -rf "$BUILD"
mkdir -p "$BUILD"

# ------------------------------------------------------------------
# 1. DTC macro header — prepended to every source that uses NEXT/PUSH/POP
# ------------------------------------------------------------------
cat > "$BUILD/_macros.h.s" <<'EOF'
// Auto-generated by build.sh — DTC macros for files that use NEXT/PUSH/POP
// without defining them (lithos-lexer.s, lithos-expr.s).
.ifndef DTC_MACROS_DEFINED
.set DTC_MACROS_DEFINED, 1
.macro NEXT
    ldr     x25, [x26], #8
    ldr     x16, [x25]
    br      x16
.endm
.macro PUSH reg
    str     x22, [x24, #-8]!
    mov     x22, \reg
.endm
.macro POP reg
    mov     \reg, x22
    ldr     x22, [x24], #8
.endm
.macro RPUSH reg
    str     \reg, [x23, #-8]!
.endm
.macro RPOP reg
    ldr     \reg, [x23], #8
.endm
.endif
EOF

# Files that DO define their own NEXT/PUSH/POP — skip prelude for these
needs_macros() {
    local f="$1"
    case "$f" in
        lithos-expr.s) return 0 ;;
        *) return 1 ;;
    esac
}

# ------------------------------------------------------------------
# 2. Patch lithos-bootstrap.s — rename _start to bootstrap_init
# ------------------------------------------------------------------
patch_bootstrap() {
    # Remove `.global _start`, rename `_start:` label to `bootstrap_init:`
    sed -e 's/^\.global _start[[:space:]]*$/.global bootstrap_init/' \
        -e '0,/^_start:[[:space:]]*$/ s//bootstrap_init:/' \
        "$1"
}

# ------------------------------------------------------------------
# 3. Generate per-file globals prelude.
#    Collect every top-level label matching well-known prefixes and
#    emit `.global` for each. This makes cross-file references resolve.
# ------------------------------------------------------------------
globals_for() {
    local src="$1"
    # Match at column 0: "<name>:" where <name> starts with one of our prefixes
    # or is a known shared symbol.
    # A "label" here is any identifier at column 0 followed by ":".
    # We only promote symbols whose prefix looks like shared bootstrap
    # infrastructure (prevents promoting unrelated internal labels).
    awk '
        /^(code_|entry_|var_|xtl_|xtf_|cfa_|emit_|lex_|parse_|elf_|drv_|do_|saved_|ls_|lithos_|bootstrap_|sym_|reg_)[A-Za-z0-9_]*:/ {
            name = $0; sub(/:.*/, "", name); print ".global " name
        }
        /^(last_entry|main_loop|mem_space|data_stack_top|ret_stack_top|data_stack_bottom|ret_stack_bottom|bootstrap_init|emit_last_entry|entry_pad|entry_ls_loop_peek|entry_lex_token_fetch|entry_emit_word|entry_lithos_lex|alloc_reg|emit32|free_reg|patch_b|patch_b_cond|reset_regs|skip_newlines|scope_depth|next_reg):/ {
            name = $0; sub(/:.*/, "", name); print ".global " name
        }
    ' "$src" | sort -u
}

# ------------------------------------------------------------------
# 4. Assemble each source with (optional) macro prelude + globals prelude
# ------------------------------------------------------------------
FAIL=0
OBJS=()
for src in "${SRCS[@]}"; do
    base="${src%.s}"
    patched="$BUILD/${base}.patched.s"
    obj="$BUILD/${base}.o"

    {
        needs_macros "$src" && cat "$BUILD/_macros.h.s"

        # Globals prelude — emit for every file
        if [ "$src" = "lithos-bootstrap.s" ]; then
            # Extract labels from the patched content, not the original
            patch_bootstrap "$src" | globals_for /dev/stdin
        else
            globals_for "$src"
        fi
        echo

        # Body
        if [ "$src" = "lithos-bootstrap.s" ]; then
            patch_bootstrap "$src"
        else
            cat "$src"
        fi
    } > "$patched"

    if ! as -o "$obj" "$patched" 2> "$BUILD/${base}.asm.err"; then
        red "ASSEMBLE FAILED: $src"
        cat "$BUILD/${base}.asm.err" >&2
        FAIL=1
        continue
    fi
    if [ -s "$BUILD/${base}.asm.err" ]; then
        yellow "warnings: $src"
        cat "$BUILD/${base}.asm.err" >&2
    fi
    OBJS+=("$obj")
done

[ $FAIL -ne 0 ] && { red "assembly failed; aborting link"; exit 1; }

# ------------------------------------------------------------------
# 5. Duplicate-symbol audit.
#    If two object files define the same global helper, report it.
# ------------------------------------------------------------------
yellow "== duplicate-symbol audit =="
dup_pairs=""
for o in "${OBJS[@]}"; do
    # Keep only GLOBAL (uppercase) defined symbols. Local (lowercase)
    # duplicates like per-file .bss scratch are safe.
    nm --defined-only "$o" 2>/dev/null | awk -v f="$o" '$2 ~ /^[A-Z]$/ && $2 !~ /[aNn]/ { print $3 " " f }'
done > "$BUILD/syms.txt"
dupes=$(awk '{print $1}' "$BUILD/syms.txt" | sort | uniq -d)
if [ -n "$dupes" ]; then
    red "DUPLICATE SYMBOLS (may be silently merged by ld as commons):"
    for sym in $dupes; do
        printf '  %s\n' "$sym"
        awk -v s="$sym" '$1==s{print "    " $2}' "$BUILD/syms.txt"
    done
else
    green "no duplicate global symbols"
fi

# ------------------------------------------------------------------
# 6. Link.
# ------------------------------------------------------------------
# Order: driver first (wins _start), then bootstrap, then chain sources.
# The DTC dictionary chain only requires that last_entry and the
# entry_* labels all be visible to the linker — order within the
# chain is encoded by the .quad forward/back pointers in .data.
yellow "== linking =="
LINK_ORDER=(
    "$BUILD/driver.o"
    "$BUILD/lithos-bootstrap.o"
    "$BUILD/lithos-lexer.o"
    "$BUILD/lithos-table.o"
    "$BUILD/lithos-expr.o"
    "$BUILD/emit-arm64.o"
    "$BUILD/lithos-elf-writer.o"
    "$BUILD/lithos-glue.o"
    "$BUILD/ls-shared.o"
)

if ! ld --warn-common --no-undefined -o lithos-bootstrap "${LINK_ORDER[@]}" 2> "$BUILD/link.err"; then
    red "LINK FAILED"
    cat "$BUILD/link.err" >&2
    exit 1
fi
if [ -s "$BUILD/link.err" ]; then
    yellow "link warnings:"
    cat "$BUILD/link.err" >&2
fi

green "built: $(pwd)/lithos-bootstrap"
ls -l lithos-bootstrap
