#!/usr/bin/env bash
# build-darwin.sh — Build the Lithos bootstrap on macOS (ARM64 / Mach-O).
#
# Same pipeline as build.sh, with three mechanical transforms:
#
#   1. ADRP/lo12 assembler dialect:
#        adrp x_, sym       → adrp x_, sym@PAGE
#        :lo12:sym           → sym@PAGEOFF
#
#   2. Syscall ABI — Linux ARM64 → Darwin ARM64:
#        .equ SYS_READ, 63  → .equ SYS_READ, 3        (Darwin BSD numbers)
#        mov x8, #SYS_*     → mov x16, #SYS_*         (Darwin uses X16)
#        mov x8, #64        → mov x16, #4              (raw number fixups)
#        svc #0              → svc #0x80                (Darwin trap)
#
#   3. Extend specifiers:
#        , uxtw\b           → , uxtw #0
#
# The source .s files are NEVER modified. Transforms happen on patched
# copies in the build directory, exactly like build.sh's existing patches.

set -euo pipefail

cd "$(dirname "$0")"

# ------------------------------------------------------------------
# 0. Parse --target argument (linux | darwin)
# ------------------------------------------------------------------
TARGET=linux
while [[ $# -gt 0 ]]; do
    case "$1" in
        --target)
            TARGET="${2:-linux}"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

BUILD=build-darwin
SRCS=(
    ls-shared.s
    lithos-bootstrap.s
    lithos-lexer.s
    lithos-table.s
    lithos-expr.s
    emit-arm64.s
    lithos-elf-writer.s
    lithos-glue.s
    driver.s
)

red()   { printf '\033[31m%s\033[0m\n' "$*" >&2; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }

rm -rf "$BUILD"
mkdir -p "$BUILD"

# ------------------------------------------------------------------
# 1. DTC macro header (same as build.sh)
# ------------------------------------------------------------------
cat > "$BUILD/_macros.h.s" <<'EOF'
// Auto-generated by build-darwin.sh — DTC macros
.ifndef DTC_MACROS_DEFINED
.set DTC_MACROS_DEFINED, 1
.macro NEXT
    ldr     x25, [x26], #8
    ldr     x16, [x25]
    br      x16
.endm
.macro PUSH reg
    str     x22, [x24, #-8]!
    mov     x22, \reg
.endm
.macro POP reg
    mov     \reg, x22
    ldr     x22, [x24], #8
.endm
.macro RPUSH reg
    str     \reg, [x23, #-8]!
.endm
.macro RPOP reg
    ldr     \reg, [x23], #8
.endm
.endif
EOF

needs_macros() {
    case "$1" in
        lithos-expr.s) return 0 ;;
        *) return 1 ;;
    esac
}

# ------------------------------------------------------------------
# 2. Patch lithos-bootstrap.s — rename _start (same as build.sh)
# ------------------------------------------------------------------
patch_bootstrap() {
    sed -e 's/^\.global _start[[:space:]]*$/.global bootstrap_init/' \
        -e '0,/^_start:[[:space:]]*$/ s//bootstrap_init:/' \
        "$1"
}

# ------------------------------------------------------------------
# 3. Per-file globals prelude (same as build.sh)
# ------------------------------------------------------------------
globals_for() {
    local src="$1"
    awk '
        /^(code_|entry_|var_|xtl_|xtf_|cfa_|emit_|lex_|parse_|elf_|drv_|do_|saved_|ls_|lithos_|bootstrap_|sym_|reg_)[A-Za-z0-9_]*:/ {
            name = $0; sub(/:.*/, "", name); print ".global " name
        }
        /^(last_entry|main_loop|mem_space|data_stack_top|ret_stack_top|data_stack_bottom|ret_stack_bottom|bootstrap_init|emit_last_entry|entry_pad|entry_ls_loop_peek|entry_lex_token_fetch|entry_emit_word|entry_lithos_lex|alloc_reg|emit32|free_reg|patch_b|patch_b_cond|reset_regs|skip_newlines|scope_depth|next_reg):/ {
            name = $0; sub(/:.*/, "", name); print ".global " name
        }
    ' "$src" | sort -u
}

# ------------------------------------------------------------------
# 4. Darwin platform transforms
# ------------------------------------------------------------------

# Transform assembly source from Linux ARM64 to Darwin ARM64.
# Three passes:
#   1. Hoist .equ constants to top WITH Darwin values (Clang needs them before use)
#   2. Delete .equ lines from body (already hoisted)
#   3. Apply all other platform transforms to body
# IMPORTANT: only hoist .equ lines, NOT .set lines — .set guards macros.
darwin_transform() {
    local input
    input=$(cat)

    # Pass 1: hoist .equ constants with Darwin platform values applied
    local hoisted
    hoisted=$(echo "$input" | grep -E '^\.equ[[:space:]]' | sed -E \
        -e 's/^(\.equ[[:space:]]+SYS_READ,[[:space:]]*)63/\13/' \
        -e 's/^(\.equ[[:space:]]+SYS_WRITE,[[:space:]]*)64/\14/' \
        -e 's/^(\.equ[[:space:]]+SYS_OPENAT,[[:space:]]*)56/\1463/' \
        -e 's/^(\.equ[[:space:]]+SYS_CLOSE,[[:space:]]*)57/\16/' \
        -e 's/^(\.equ[[:space:]]+SYS_LSEEK,[[:space:]]*)62/\1199/' \
        -e 's/^(\.equ[[:space:]]+SYS_EXIT,[[:space:]]*)93/\11/' \
        -e 's/^(\.equ[[:space:]]+SYS_MMAP,[[:space:]]*)222/\1197/' \
        -e 's/^(\.equ[[:space:]]+SYS_BRK,[[:space:]]*)214/\112/' \
        -e 's/^(\.equ[[:space:]]+SYS_MUNMAP,[[:space:]]*)215/\173/' \
        -e 's/^(\.equ[[:space:]]+SYS_FSTAT,[[:space:]]*)80/\1339/' \
        -e 's/^(\.equ[[:space:]]+AT_FDCWD,[[:space:]]*)-100/\1-2/' \
        -e 's/^(\.equ[[:space:]]+O_WCT,[[:space:]]*)577/\11537/' \
        || true)

    # If --target darwin, rewrite ARM64_SVC_0 so compiled output emits SVC #0x80.
    # Matches both flat form (0xD4000001) and split form ((0xD400 << 16) | 0x0001).
    if [ "$TARGET" = "darwin" ]; then
        hoisted=$(echo "$hoisted" | sed -E \
            -e 's/^(\.equ[[:space:]]+ARM64_SVC_0,[[:space:]]*)0xD4000001/\10xD4001001/' \
            -e 's/^(\.equ[[:space:]]+ARM64_SVC_0,.*\| *)0x0001/\10x1001/' \
        )
    fi
    echo "$hoisted"

    # Pass 2: transform body (.equ deleted — already hoisted with correct values)
    echo "$input" | sed -E \
        -e '/^\.equ[[:space:]]/d' \
        -e 's/adrp[[:space:]]+(x[0-9]+|x[12][0-9]|x30),[[:space:]]*([a-zA-Z_][a-zA-Z0-9_]*)/adrp \1, \2@PAGE/g' \
        -e 's/:lo12:([a-zA-Z_][a-zA-Z0-9_]*)/\1@PAGEOFF/g' \
        \
        -e 's/mov[[:space:]]+x8,[[:space:]]*#SYS_/mov x16, #SYS_/g' \
        -e 's/mov[[:space:]]+x8,[[:space:]]*#64([[:space:]]*\/\/.*SYS_WRITE)/mov x16, #4\1/g' \
        -e 's/mov[[:space:]]+x8,[[:space:]]*#93([[:space:]]*\/\/.*SYS_EXIT)/mov x16, #1\1/g' \
        -e 's/mov[[:space:]]+x8,[[:space:]]*#56([[:space:]]*\/\/.*SYS_OPENAT)/mov x16, #463\1/g' \
        -e 's/mov[[:space:]]+x8,[[:space:]]*#222([[:space:]]*\/\/.*SYS_MMAP)/mov x16, #197\1/g' \
        \
        -e 's/svc[[:space:]]+#0([^x0-9]|$)/svc #0x80\1/g' \
        \
        -e 's/,[[:space:]]*(x)([0-9]+),[[:space:]]*uxtw/, w\2, uxtw/g' \
        \
        -e 's/mov[[:space:]]+(x[0-9]+),[[:space:]]*#0x22([[:space:]]*\/\/.*MAP_PRIVATE\|MAP_ANONYMOUS)/mov \1, #0x1002\2/g' \
        -e 's/mov[[:space:]]+(x[0-9]+),[[:space:]]*#0x22$/mov \1, #0x1002/g' \
        \
        -e 's/^(interp_return_xt:)/.data\n.align 3\n\1/' \
        \
        -e 's/ldr[[:space:]]+x15,[[:space:]]*\[sp\][[:space:]]*$/mov x15, x0/g' \
        -e 's/add[[:space:]]+x16,[[:space:]]*sp,[[:space:]]*#8[[:space:]]*$/mov x16, x1/g' \
        -e '/^[[:space:]]*\.quad[[:space:]]+interp_return_code/a\
.text' \
    | awk '
    # Invert conditional branches to external labels.
    # ARM64 b.cond has limited range; Mach-O requires local targets.
    # b.cond external → b.!cond .Lbskip_N; b external; .Lbskip_N:
    BEGIN { n=0 }
    /^[[:space:]]+b\.(eq|ne|lt|ge|gt|le|lo|hs|hi|ls|cs|cc|mi|pl|vs|vc)[[:space:]]+[a-zA-Z_]/ {
        target = $2
        if (target ~ /^\.L/ || target ~ /^[0-9]/) { print; next }
        cond = $1; sub(/b\./, "", cond)
        split("eq:ne ne:eq lt:ge ge:lt gt:le le:gt lo:hs hs:lo hi:ls ls:hi cs:cc cc:cs mi:pl pl:mi vs:vc vc:vs", pairs)
        inv = ""
        for (i in pairs) {
            split(pairs[i], kv, ":")
            if (kv[1] == cond) { inv = kv[2]; break }
        }
        if (inv == "") { print; next }
        n++
        printf "    b.%s .Lbskip_%d\n", inv, n
        printf "    b %s\n", target
        printf ".Lbskip_%d:\n", n
        next
    }
    { print }
    '
}

# ------------------------------------------------------------------
# 4b. Driver patch: replace DTC pipeline with native calls.
#     The DTC trampoline has an unresolved issue on macOS (produces
#     zero code output). Native calls (bl do_lithos_lex, bl parse_tokens)
#     work correctly. This patches driver.s only.
# ------------------------------------------------------------------
driver_native_patch() {
    python3 -c "
import sys
lines = sys.stdin.readlines()
out = []
skip = False
for i, line in enumerate(lines):
    if '// Push src-addr, src-len onto data stack' in line:
        skip = True
        out.append('''
    // ====== NATIVE PIPELINE (bypasses DTC trampoline) ======
    // Call do_lithos_lex(x0=src_buf, x1=src_len)
    mov     x0, x19
    mov     x1, x18
    stp     x19, x18, [sp, #-16]!
    bl      do_lithos_lex
    ldp     x19, x18, [sp], #16

    // Call parse_tokens(x0=token_buf, x1=token_count, x2=src_buf)
    adrp    x0, ls_token_count@PAGE
    add     x0, x0, ls_token_count@PAGEOFF
    ldr     x1, [x0]
    adrp    x0, ls_token_buf@PAGE
    add     x0, x0, ls_token_buf@PAGEOFF
    mov     x2, x19
    stp     x19, x18, [sp, #-16]!
    bl      parse_tokens
    ldp     x19, x18, [sp], #16

    // Push (code_buf, code_pos) onto DTC stack for ELF writer
    adrp    x0, ls_code_buf@PAGE
    add     x0, x0, ls_code_buf@PAGEOFF
    str     x22, [x24, #-8]!
    mov     x22, x0
    adrp    x0, ls_code_pos@PAGE
    add     x0, x0, ls_code_pos@PAGEOFF
    ldr     x0, [x0]
    str     x22, [x24, #-8]!
    mov     x22, x0
    // ====== END NATIVE PIPELINE ======

''')
        continue
    if skip and '// Branch on target for write' in line:
        skip = False
    if skip:
        continue
    out.append(line)
sys.stdout.writelines(out)
"
}

# ------------------------------------------------------------------
# 5. Assemble each source
# ------------------------------------------------------------------
FAIL=0
OBJS=()
for src in "${SRCS[@]}"; do
    base="${src%.s}"
    patched="$BUILD/${base}.patched.s"
    obj="$BUILD/${base}.o"

    {
        needs_macros "$src" && cat "$BUILD/_macros.h.s"

        # Globals prelude
        if [ "$src" = "lithos-bootstrap.s" ]; then
            patch_bootstrap "$src" | globals_for /dev/stdin
        else
            globals_for "$src"
        fi
        echo

        # Body with platform transforms
        if [ "$src" = "lithos-bootstrap.s" ]; then
            patch_bootstrap "$src" | darwin_transform
        elif [ "$src" = "driver.s" ]; then
            darwin_transform < "$src" | driver_native_patch
        else
            darwin_transform < "$src"
        fi
    } > "$patched"

    # Use clang -c instead of as: it handles conditional branches to
    # external labels via automatic relaxation (as rejects them on ARM64).
    if ! clang -c -x assembler -target arm64-apple-macos -mrelax-all \
              -o "$obj" "$patched" 2> "$BUILD/${base}.asm.err"; then
        red "ASSEMBLE FAILED: $src"
        cat "$BUILD/${base}.asm.err" >&2
        FAIL=1
        continue
    fi
    if [ -s "$BUILD/${base}.asm.err" ]; then
        yellow "warnings: $src"
        cat "$BUILD/${base}.asm.err" >&2
    fi
    OBJS+=("$obj")
done

[ $FAIL -ne 0 ] && { red "assembly failed; aborting link"; exit 1; }

# ------------------------------------------------------------------
# 6. Duplicate-symbol audit (macOS nm syntax)
# ------------------------------------------------------------------
yellow "== duplicate-symbol audit =="
for o in "${OBJS[@]}"; do
    nm -g -U "$o" 2>/dev/null | awk -v f="$o" '/ [TtDdBb] / { print $3 " " f }'
done > "$BUILD/syms.txt"
dupes=$(awk '{print $1}' "$BUILD/syms.txt" | sort | uniq -d)
if [ -n "$dupes" ]; then
    red "DUPLICATE SYMBOLS:"
    for sym in $dupes; do
        printf '  %s\n' "$sym"
        awk -v s="$sym" '$1==s{print "    " $2}' "$BUILD/syms.txt"
    done
else
    green "no duplicate global symbols"
fi

# ------------------------------------------------------------------
# 7. Link (macOS ld)
# ------------------------------------------------------------------
yellow "== linking =="
LINK_ORDER=(
    "$BUILD/driver.o"
    "$BUILD/lithos-bootstrap.o"
    "$BUILD/lithos-lexer.o"
    "$BUILD/lithos-table.o"
    "$BUILD/lithos-expr.o"
    "$BUILD/emit-arm64.o"
    "$BUILD/lithos-elf-writer.o"
    "$BUILD/lithos-glue.o"
    "$BUILD/ls-shared.o"
)

# macOS requires linking against libSystem even for raw-syscall binaries.
# The kernel won't load a process without the dyld chain set up.
# -e _start: custom entry point (not _main)
# -lSystem: provides dyld bootstrap + syscall stubs
SDK_PATH=$(xcrun --sdk macosx --show-sdk-path)
if ! ld -o lithos-bootstrap-darwin \
       -e _start \
       -platform_version macos 15.0.0 15.0.0 \
       -lSystem -L"${SDK_PATH}/usr/lib" \
       "${LINK_ORDER[@]}" 2> "$BUILD/link.err"; then
    red "LINK FAILED"
    cat "$BUILD/link.err" >&2
    exit 1
fi
if [ -s "$BUILD/link.err" ]; then
    yellow "link warnings:"
    cat "$BUILD/link.err" >&2
fi

green "built: $(pwd)/lithos-bootstrap-darwin"
ls -l lithos-bootstrap-darwin
