#!/usr/bin/env bash
# compile-darwin.sh — Compile .ls source to a macOS ARM64 executable.
#
# The bootstrap compiles .ls to raw ARM64 machine code wrapped in ELF.
# This script extracts the machine code and re-wraps it in Mach-O via
# the system assembler+linker (which handle all Mach-O complexity).
#
# Usage: ./compile-darwin.sh input.ls [-o output]
#
# The compiled .ls program uses Darwin syscalls (x16, svc #0x80).
# Source .ls that uses Linux syscall conventions (x8, svc #0) will
# assemble but crash at runtime — the .ls source itself must be
# written for the target platform.

set -euo pipefail
cd "$(dirname "$0")"

BOOTSTRAP=./lithos-bootstrap-darwin
SDK_PATH=$(xcrun --sdk macosx --show-sdk-path)
TMP=$(mktemp -d /tmp/lithos-darwin-XXXXXX)
trap "rm -rf $TMP" EXIT

# Parse args
INPUT=""
OUTPUT="a.out"
while [ $# -gt 0 ]; do
    case "$1" in
        -o) OUTPUT="$2"; shift 2 ;;
        *)  INPUT="$1"; shift ;;
    esac
done

[ -z "$INPUT" ] && { echo "usage: $0 input.ls [-o output]" >&2; exit 1; }
[ -f "$INPUT" ] || { echo "error: $INPUT not found" >&2; exit 1; }
[ -x "$BOOTSTRAP" ] || { echo "error: run ./build-darwin.sh first" >&2; exit 1; }

# Step 1: Compile .ls → ELF via bootstrap
"$BOOTSTRAP" "$INPUT" -o "$TMP/raw.elf"

# Step 2: Extract .text from ELF
# The bootstrap produces a minimal ELF: 64-byte header + 56-byte phdr + .text
# .text starts at offset 120 (0x78), length = filesize - 120
FILESIZE=$(wc -c < "$TMP/raw.elf" | tr -d ' ')
TEXT_SIZE=$((FILESIZE - 120))

if [ "$TEXT_SIZE" -le 0 ]; then
    echo "error: empty .text section" >&2
    exit 1
fi

dd if="$TMP/raw.elf" of="$TMP/text.bin" bs=1 skip=120 count="$TEXT_SIZE" 2>/dev/null

# Step 3: Wrap raw machine code in a macOS assembly file
{
    echo "// Auto-generated by compile-darwin.sh"
    echo ".global _start"
    echo ".text"
    echo ".align 4"
    echo "_start:"
    # Emit raw bytes as .byte directives (16 per line)
    xxd -p "$TMP/text.bin" | fold -w32 | while read -r line; do
        bytes=""
        for ((i=0; i<${#line}; i+=2)); do
            [ -n "$bytes" ] && bytes="$bytes, "
            bytes="${bytes}0x${line:$i:2}"
        done
        echo "    .byte $bytes"
    done
} > "$TMP/wrap.s"

# Step 4: Assemble + link → Mach-O
as -o "$TMP/wrap.o" "$TMP/wrap.s"
ld -o "$OUTPUT" \
    -e _start \
    -platform_version macos 15.0.0 15.0.0 \
    -lSystem -L"${SDK_PATH}/usr/lib" \
    "$TMP/wrap.o"

echo "lithos: wrote $OUTPUT (Mach-O)"
ls -l "$OUTPUT"
